### ISSUE TITLE
App not compatible with Homey 2.0

### ISSUE THREAD

**Issue by lirand84** [mhaid/de.mhaid.permundo#1]
Hello. Many thanks for your work.
Are you planning an update for the Permundo app to be compatible with Homey 2.0, and if so, when?
Is there a way to install the current app on Homey 2.0?
<img width="396" alt="bildschirmfoto 2019-03-06 um 14 15 16" src="https://user-images.githubusercontent.com/48285387/53884187-46585700-401b-11e9-813d-4386ea95a2ee.png">

**Comment by mhaid** [comment]
Hello @lirand84 ,
Thanks for the comment.

We have now updated the app to be compatible with Homey V2.x and are currently waiting for validation.

If any problems occur, please let us know.

Kind regards
